// Mocks generated by Mockito 5.4.3 from annotations
// in stock_scan_parser/test/domain_layer/usecases/fetch_stock_scan_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stock_scan_parser/data_layer/data_layer.dart' as _i2;
import 'package:stock_scan_parser/domain_layer/domain_layer.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchStockDataRemote_0 extends _i1.SmartFake
    implements _i2.FetchStockDataRemote {
  _FakeFetchStockDataRemote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchStockScanRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchStockScanRepoImpl extends _i1.Mock
    implements _i2.FetchStockScanRepoImpl {
  @override
  _i2.FetchStockDataRemote get fetchStockDataSource => (super.noSuchMethod(
        Invocation.getter(#fetchStockDataSource),
        returnValue: _FakeFetchStockDataRemote_0(
          this,
          Invocation.getter(#fetchStockDataSource),
        ),
        returnValueForMissingStub: _FakeFetchStockDataRemote_0(
          this,
          Invocation.getter(#fetchStockDataSource),
        ),
      ) as _i2.FetchStockDataRemote);

  @override
  _i4.Future<_i3.Either<_i5.Failure, List<_i5.StockScanEntity>>>
      fetchStockScan() => (super.noSuchMethod(
            Invocation.method(
              #fetchStockScan,
              [],
            ),
            returnValue: _i4.Future<
                    _i3.Either<_i5.Failure, List<_i5.StockScanEntity>>>.value(
                _FakeEither_1<_i5.Failure, List<_i5.StockScanEntity>>(
              this,
              Invocation.method(
                #fetchStockScan,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i3.Either<_i5.Failure, List<_i5.StockScanEntity>>>.value(
                _FakeEither_1<_i5.Failure, List<_i5.StockScanEntity>>(
              this,
              Invocation.method(
                #fetchStockScan,
                [],
              ),
            )),
          ) as _i4.Future<_i3.Either<_i5.Failure, List<_i5.StockScanEntity>>>);
}
